### ISSUE TITLE
Create a Custom ImageView

### ISSUE THREAD

**Issue by Shubham0812** [Shubham0812/DailyTracker_UI#5]
## Requirement
We need an Image View struct that takes in an image, is scalable based on the frame provided by the Parent View. 
Display a circular image with a border around the image, should be fully customisable through variables.

## Proposed solution
Create a generic Image View Struct under Common > Views > Support Views.

Add variables that takes in an **imageName**, **lineWidth** and **borderColor**.

The View that you should create should look something similar to this- 
![Screenshot 2021-10-14 at 2 28 23 PM](https://user-images.githubusercontent.com/19903539/137285522-8be14cd9-b225-437a-9560-44146c7738a6.png)

Once you're done raise a PR. Good luck :)

**Comment by Yashraj49** [comment]
hello @Shubham0812 I I want to work on this as I am very new to this it will be good challenge for me

**Comment by Shubham0812** [comment]
Hey Yash, sure, I'll assign it to you :D

**Comment by Yashraj49** [comment]
hey @Shubham0812 I have raised PR #7  you may now review it .
